language: node_js
node_js:
  - "lts/*"
cache:  
  directories:
    - "node_modules"
sudo: false
install:
  - npm clean-install 
script:
  - echo "build index.html"
  - npm run build

notifications:
  email:
    on_success: change
    on_failure: change
